### ISSUE TITLE
The presence of a (.rsp) file causes problems.

### ISSUE THREAD

**Issue by chibanemourad** [daveaglick/Buildalyzer#211] opened 2022-08-09 16:26 UTC
Hello 
First of all, thank you for this very useful tool. 
I noticed that the presence of a [**`.rsp`**](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-response-files?view=vs-2022) file containing `/bl` argument in the tree structure of a `.csproj` causes a problem when calling the `Build()` method on a `ProjectAnalyzer`.

I pushed a repository to reproduce the bug here: [AutoResponseFileIssueRepro](https://github.com/chibanemourad/AutoResponseFileIssueRepro)

**Comment by daveaglick** [comment] 2022-08-18 15:19
Interesting, thanks for the repro!

I'm assuming you're talking about a `Directory.Build.rsp` file? As far as I know a `MSBuild.rsp` wouldn't get picked up if it's not in the same directory as MSBuild itself. But I guess either way, the problem is really that the `/bl` flag is conflicting with the logging configuration Buildalyzer has to do.

To be honest I'm not sure how that can be resolved. Buildalyzer works at a foundational level by running MSBuild and instrumenting it with a custom logger that feeds build events back to Buildalyzer over a pipe (which Buildalyzer can then collect and analyze). Given that an `.rsp` file defines the behavior of MSBuild when run, and if that `.rsp` file has anything that conflicts with what Buildalyzer is doing, I can see how they'd be incompatible. I've just got no ideas on how to fix it :/. Any thoughts?

**Comment by daveaglick** [comment] 2022-08-18 15:21
I guess we could globally disable response files when Buildalyzer is run. That's not ideal because the `.rsp` might have other important flags, but it's probably better than crashing or breaking.

**Comment by daveaglick** [comment] 2022-08-18 17:34
Fix is committed and will go out with the next release (not sure when that'll be, probably later this week or next).

**Closed by daveaglick** 2022-08-18 17:34 UTC
