### ISSUE TITLE
Unable to dispose _projectReferences from AnalyzerResultExtensions

### ISSUE THREAD

**Issue by wadinj** [daveaglick/Buildalyzer#87] opened 2018-10-16 22:46 UTC
Hi,

First thanks for your awesome works on this support of workspace for .NET CORE.

I'm creating a AdhocWorkspace to retrieve the syntax tree from the compilation object of bunch of projects. To do that I use :

```
var manager = new AnalyzerManager(solutionPath);
foreach (var project in manager.Projects)
{
        projects.Add(project.Value.AddToWorkspace(workspace));
}
```
I noticed a memory leak while using this under a REST endpoint (web server).  Under AnalyzerResultExtensions, you feed a ConcurrentDictionary with the project references (variable : _projectReferences). Each time we compile another project without stop and start our process this dictionary is growing a lot with all the references project. It seems to have no way to access this Dictionary and clear/reset it. 

Do you agree to add a Dispose or ClearReferences method on AnalyzerResultExtensions to reset and re-assign the _projectReferences dictionary ? 

Thanks,
Jonathan

**Comment by daveaglick** [comment] 2018-10-16 23:39
I’m generally not a huge fan of “reset” style APIs. I prefer the lifetime of objects to appropriately reflect when and how long data should be referenced or garbage collected.

In this case I can see where the problem is - good find. Since it’s in a static extension class, there’s no object to act as a transient container for the cache. I’m going to think on this a little bit - while your solution gets the job done, I’d still prefer to connect the cache to an object that will go out of scope when appropriate. Maybe I can put the cache inside the `AnalyzerManager` or have the user pass it in when calling one of the extension methods.

**Comment by wadinj** [comment] 2018-10-16 23:46
@daveaglick Oh right, yes I agree this solution is not the best at all but I didn't figure out where to place it or implement IDisposable somewhere. 

Let me know if you need help or what you have in mind, I can write a piece of code there!

Thanks again

**Comment by wadinj** [comment] 2018-10-19 18:31
Hi Dave, 

Do you have think about a long-term solution. I can move the array to the AnalyzerManager and make it disposable and clear the static _projectReferences on the Dispose method. What do you think ?

**Comment by daveaglick** [comment] 2018-11-01 20:09
Hey - sorry for the delay! Finally getting back to this project. I'll take one more look to refresh myself and get back to you tomorrow and we can get this resolved.

**Comment by daveaglick** [comment] 2018-11-02 13:10
I merged in your PR (so you'd get credit) and then ended up moving the cache to the `AnalyzerManager`. It doesn't need to be static or disposed - it'll go out of scope when the `AnalyzerManager` does and get collected on the next GC pass like everything else. The whole process should be automatic provided you're not keeping `AnalyzerManager` instances hanging around.

**Closed by daveaglick** 2018-11-02 13:10 UTC
Labels: Bug

**Comment by wadinj** [comment] 2018-11-02 16:03
Excellent, 
Thanks Dave
